spring:
  datasource:
    url: jdbc:h2:mem:newdb
    username: root
    password: Tramonto13139609
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

fileRepositoryFolder: C:\Users\DELL\OneDrive\Desktop\fileFolder
